export const HOME_ROUTE = '/'
export const LOGIN_ROUTE = '/login' 
export const LEARN_ROUTE = '/learn'
export const FORUM_ROUTE = '/forum'
export const ADMIN_ROUTE = '/admin'
export const PROFILE_ROUTE = '/profile'
